### ISSUE TITLE
Автоматическая синхронизация с файлами шаблонов

### ISSUE THREAD

**Issue by rinekri** [rougsig/file-template-loader#12]
Сейчас приходится синхронизировать вручную через выпадающую панель, и постоянно об этом забываешь.

**Comment by rougsig** [comment]
Убрал кэш шаблонов. Шаблоны сами апдейтся, но не индексируются. Чтобы новый шаблон повявился в списке, все же нужно нажать кнопку.

(Если у шаблонов, есть зависимости, на не индексированые шаблоны, все будет окей. Но список не перебилдится сам)
