### ISSUE TITLE
Неочевидна разница между FILE_NAME и SIMPLE_NAME

### ISSUE THREAD

**Issue by rinekri** [rougsig/file-template-loader#15]

**Comment by rougsig** [comment]
Как тогда назвать FILE_NAME ? Может просто везде SIMPLE_NAME провайдить?

**Comment by rougsig** [comment]
file_name он в рамках одного файла. А simple_name есть везде. Как по мне это две разные сущности.

**Comment by rinekri** [comment]
Я бы оставил только один. Неудобно и неочевидно, когда у тебя в структуре групп фигурирует fileName, а потом вдруг появляется какой-то SIMPLE_NAME и я должен был откуда-то об этом знать.

**Comment by rougsig** [comment]
Больше нету SIMPLE_NAME
FILE_NAME - имя файла с расширением
