### ISSUE TITLE
Проблема с файлами без названия (например, .gitignore)

### ISSUE THREAD

**Issue by rinekri** [rougsig/file-template-loader#19]
Например, нужно создать файл .gitignore.

Создаю шаблон GitIgnore.txt.ft, а в templates прописываю:
```json
        {
          "template": "GitIgnore.txt",
          "fileName": ".gitignore"
        }
```
В итоге получаю файл .gitignore.txt.
Хотя он должен быть без дополнительного расширения.
Если шаблон назвать .GitIgnore.ft, то создастся .gitignore.Gitignore.

**Comment by dimsuz** [comment]
Нужно учитывать, что у файлов не обязательно будет расширение...

**Comment by rougsig** [comment]
По идее .gitignore -> расширение. То есть файл .gitignore  не имеет имени.
Так что:
```json
        {
          "template": "GitIgnore.txt",
          "fileName": ""
        }
```

Можно сделать, чтобы ты сам в fileName писал и имя, и расширение

**Comment by rougsig** [comment]
Добавил в тесты .gitignore
```json
{
  "name": "Repository",
  "moduleName": "${PROJECT_NAME_LOWER_KEBAB_CASE}-${FLOW_NAME_LOWER_KEBAB_CASE}-repository",
  "sourceSets": [
    {
      "directory": "src/main/kotlin/repositories",
      "templates": [
        {
          "template": "Repository.kt.ft",
          "fileName": "${FLOW_NAME}Repository"
        },
        {
          "template": "RepositoryImpl.kt.ft",
          "fileName": "${FLOW_NAME}RepositoryImpl"
        },
        {
          "template": "RepositoryBindings.kt.ft",
          "fileName": "${FLOW_NAME}RepositoryBindings",
          "directory": "di"
        }
      ]
    },
    {
      "templates": [
        {
          "template": ".gitignore.ft",
          "fileName": ""
        }
      ]
    }
  ]
}
```

**Comment by dimsuz** [comment]
> По идее .gitignore -> расширение. То есть файл .gitignore не имеет имени.

Это ошибочное суждение. Взращённая виндой логика ;)

В линуксе и маке (unix based системах) у файлов многих нет расширения - они, скорее, наоборот стали там появляться под влиянием винды постепенно. До этого всё работало чисто на системе mime-types с анализом первых байтов в файлах (и сейчас частично работает).

Так что `.gitignore` - это файл без расширения, у которого имя начинается с точки.
В Unix-системах точка в начале имени файла или директории просто означает, что это скрытый файл - и файловые менеджеры (и команда ls) их прячут по умолчанию.

Исходя из этого, тебе не стоит трактовать это как файл без имени, а стоит трактовать, как файл без расширения. То есть, нужно убедиться, что файлы

```
WORKSPACE (привет bazel)
.gitignore
Makefile
etc
```
будут корректно поддерживаться. Расширение опционально, имя же обязательно.

**Comment by dimsuz** [comment]
```
      "templates": [
        {
          "template": ".gitignore.ft",
          "fileName": ""
        }
      ]
```
Вот это в результате крайне нелогично выглядит для linux-mac людей.

Я бы ожидал такое

```
      "templates": [
        {
          "template": ".gitignore.ft",
          "fileName": ".gitignore"
        }
      ]
```

Предложил бы переотркыть эту issue и поправить. Иначе, тебе её забьют другие.

**Comment by rougsig** [comment]
Хм... В таком случае из POJO нужно убрать поле `extension`

**Comment by rougsig** [comment]
А что есть `расширение` ?

**Comment by dimsuz** [comment]
Ага, возможно (я не до конца здесь в контексте). Может сделать его тоже опциональным.

**Comment by rougsig** [comment]
Может тогда просто в `template` указывать полное имя шаблона `.gitignore.ft`, а в `fileName` полное имя, которое ты хочешь получить в результате.
Как тут
```json
"templates": [
        {
          "template": ".gitignore.ft",
          "fileName": ".gitignore"
        }
      ]
```

В итоге будет что-то такое:
```json
 "templates": [
        {
          "template": "Repository.kt.ft",
          "fileName": "${FLOW_NAME}Repository.kt"
        },
```

**Comment by dimsuz** [comment]
> А что есть `расширение` ?

Для unix-систем - "расширение" - это чистая договорённость. если в имени файла есть точка, и она не первая (означающая скрытость), то всё, что после неё, считается расширением.

Но пользуются этим только DE типа GNOME, KDE итд - внутри своих файловых менеджеров. Типа как доп. эвристика, для определения какой прогой открывать. Для файловой системы - это всё пофигу, она видит только имя файла из набора символов.

**Comment by dimsuz** [comment]
> Может тогда просто в `template` указывать полное имя шаблона `.gitignore.ft`, а в `fileName` полное имя, которое ты хочешь получить в результате.

Мне кажется весьма логичным и в примерах этих тоже вроде всё ясно. Может Илья ещё что-то из опыта использования подскажет (я ещё не сильно погрузился в новый формат)

**Comment by rinekri** [comment]
> Может тогда просто в `template` указывать полное имя шаблона `.gitignore.ft`, а в `fileName` полное имя, которое ты хочешь получить в результате.
> Как тут
> 
> ```json
> "templates": [
>         {
>           "template": ".gitignore.ft",
>           "fileName": ".gitignore"
>         }
>       ]
> ```
> 
> В итоге будет что-то такое:
> 
> ```json
>  "templates": [
>         {
>           "template": "Repository.kt.ft",
>           "fileName": "${FLOW_NAME}Repository.kt"
>         },
> ```

Выглядит как успех :)

**Comment by rougsig** [comment]
В общем успех выглядит так:

```json
{
      "textFrom": ".gitignore.ft",
      "customProps": [
        {
          "name": "FILE_NAME",
          "text": ".gitignore"
        }
      ]
}
```
