### ISSUE TITLE
Не получается использовать  рутовый пакет вместо PACKAGE_NAME

### ISSUE THREAD

**Issue by rinekri** [rougsig/file-template-loader#22]
Сейчас если использовать PACKAGE_NAME в шаблоне, то при создании группы подставляется пакет с названием директории, и достучаться до PACKAGE_NAME оригинального, без этой директории, невозможно. А это бывает полезно для R-файлов. Если попытаться создать такую переменную в миксинах, то возникает циклическая зависимость.

**Comment by rougsig** [comment]
Добавил ROOT_PACKAGE_NAME
