### ISSUE TITLE
Добавить поддержку LOWER_DOT_CASE

### ISSUE THREAD

**Issue by dimsuz** [rougsig/file-template-loader#25]
Пытался сделать:

```
    "MODULE_PACKAGE_SUFFIX": "ui.${SCREEN_NAME_LOWER_DOT_CASE}"
```

Не паллучилось :)

**Comment by dimsuz** [comment]
Имея: "AuthVerification" хочу package "auth.verification"

**Comment by rougsig** [comment]
Хорошо. Добавлю.  Сейчас есть только такие:

LOWER_CAMEL_CASE
UPPER_CAMEL_CASE
LOWER_SNAKE_CASE
UPPER_SNAKE_CASE
LOWER_KEBAB_CASE
UPPER_KEBAB_CASE
DOT_CASE
SLASH_CASE
SOLID_CASE
UPPER_CASE
LOWER_CASE
APPEND_DOT_CASE

PS недавно узнал что kebab-case ещё называют как skewer-case

**Comment by rougsig** [comment]
Точно. Есть просто DOT_CASE, потому что он и так будет LOWER, типо тебе скорее всего будет не нужен UPPER_DOT_CASE
