### ISSUE TITLE
Нужно переименовать модификатор PACKAGE_CASE

### ISSUE THREAD

**Issue by rinekri** [rougsig/file-template-loader#9]
Сейчас непонятно что делает этот модификатор. По факту он форматирует строку через точки - надо как-то исходя из этого его и назвать.

**Comment by rinekri** [comment]
DOT_CASE?

**Comment by rougsig** [comment]
Добавил DOT_CASE, работает так же как и PACKAGE_CASE.
PACKAGE_CASE  пока не удалял
